driver.id
driver.email
driver.first_name
driver.last_name
driver.phone
driver.phone_ext
driver.time_zone
driver.metric_units
driver.carrier_name
driver.carrier_street
driver.carrier_city
driver.carrier_state
driver.carrier_zip
driver.violation_alerts
driver.terminal_street
driver.terminal_city
driver.terminal_state
driver.terminal_zip
driver.cycle
driver.exception_24_hour_restart
driver.exception_8_hour_break.class
driver.exception_wait_time
driver.exception_short_haul
driver.exception_ca_farm_school_bus
driver.cycle2
driver.exception_24_hour_restart2
driver.exception_8_hour_break2
driver.exception_wait_time2
driver.exception_short_haul2
driver.exception_ca_farm_school_bus2
driver.export_combined
driver.export_recap
driver.export_odometers
driver.drivername
driver.driver_company_id
driver.minute_logs
driver.duty_status
driver.eld_mode
driver.drivers_license_number
driver.drivers_license_state
driver.yard_moves_enabled
driver.personal_conveyance_enabled
driver.manual_driving_enabled
driver.role
driver.status






new_update_driver.driver_internal_id
new_update_driver.external_id
new_update_driver.email
new_update_driver.first_name
new_update_driver.last_name
new_update_driver.phone
new_update_driver.phone_ext
new_update_driver.image
new_update_driver.emergency_contact_name
new_update_driver.emergency_contact_phone
new_update_driver.time_zone
new_update_driver.metric_units
new_update_driver.carrier_name
new_update_driver.carrier_street
new_update_driver.carrier_city
new_update_driver.carrier_state
new_update_driver.carrier_zip
new_update_driver.violation_alerts
new_update_driver.terminal_street
new_update_driver.terminal_city
new_update_driver.terminal_state
new_update_driver.terminal_zip
new_update_driver.cycle
new_update_driver.exception_24_hour_restart
new_update_driver.exception_8_hour_break
new_update_driver.exception_wait_time
new_update_driver.exception_short_haul
new_update_driver.exception_ca_farm_school_bus
new_update_driver.cycle2
new_update_driver.exception_24_hour_restart2
new_update_driver.exception_8_hour_break2
new_update_driver.exception_wait_time2
new_update_driver.exception_short_haul2
new_update_driver.exception_ca_farm_school_bus2
new_update_driver.export_combined
new_update_driver.export_recap
new_update_driver.export_odometers
new_update_driver.username
new_update_driver.driver_company_id
new_update_driver.minute_logs
new_update_driver.duty_status
new_update_driver.eld_mode
new_update_driver.drivers_license_number
new_update_driver.drivers_license_state
new_update_driver.yard_moves_enabled
new_update_driver.personal_conveyance_enabled
new_update_driver.manual_driving_enabled
new_update_driver.status
new_update_driver.role




